parameters:
  admin_pages_to_update:
    - BazaR
    - GererSite
    - GererDroits
    - GererMisesAJour
    - GererThemes
    - GererConfig
    - GererUtilisateurs
    - GererMotsClef
    - TableauDeBord
    - LookWiki